################################################################################
# Woodpecker CI Pipeline - Branch Cleanup Automation
# Part of Feature 4: Branch Management Automation
#
# This pipeline runs on a daily schedule to automatically:
# 1. Detect stale and abandoned branches
# 2. Warn on PRs with stale branches
# 3. Delete merged branches (after retention period)
#
# Schedule: Runs daily at midnight UTC
#
# Safety Features:
# - Protected branches are never deleted
# - Configurable retention periods
# - Dry-run mode for testing
# - All actions logged to database
# - Notifications sent for deletions
################################################################################

when:
  event: cron
  cron: "0 0 * * *"  # Daily at midnight UTC

# Environment variables
environment:
  BRANCH_STALE_DAYS: 30
  BRANCH_ABANDONED_DAYS: 60
  MERGED_RETENTION_DAYS: 7
  LOG_TO_DB: "true"
  DRY_RUN: "false"  # Set to "true" for testing

steps:
  ######################################
  # Step 1: Detect Stale Branches
  ######################################
  detect-stale:
    image: android-ci:latest
    name: "Detect Stale Branches"
    environment:
      STALE_DAYS: "${BRANCH_STALE_DAYS}"
      ABANDONED_DAYS: "${BRANCH_ABANDONED_DAYS}"
      OUTPUT_FORMAT: "json"
      OUTPUT_FILE: "build/stale-branches-report.json"
    commands:
      - echo "=== Detecting Stale Branches ==="
      - mkdir -p build

      # Run stale branch detection
      - ./pipeline-utils/scripts/detect-stale-branches.sh
          --stale-days "$${STALE_DAYS}"
          --abandoned-days "$${ABANDONED_DAYS}"
          --format "$${OUTPUT_FORMAT}"
          --output "$${OUTPUT_FILE}"

      # Display summary
      - echo ""
      - echo "Stale branches detected. Report saved to $${OUTPUT_FILE}"

      # Upload report as artifact (if supported)
      - if [ -f "$${OUTPUT_FILE}" ]; then
          echo "Report size: $(wc -c < "$${OUTPUT_FILE}") bytes";
        fi
    when:
      - event: cron

  ######################################
  # Step 2: Warn on Stale PRs
  ######################################
  warn-stale:
    image: android-ci:latest
    name: "Warn Stale PRs"
    environment:
      STALE_DAYS: "${BRANCH_STALE_DAYS}"
      ABANDONED_DAYS: "${BRANCH_ABANDONED_DAYS}"
      MENTION_TEAM: "false"
      MENTION_ASSIGNEES: "true"
      DRY_RUN: "${DRY_RUN}"
    commands:
      - echo "=== Warning on Stale PRs ==="

      # Check for gh CLI
      - if ! command -v gh &> /dev/null; then
          echo "WARNING: gh CLI not found. Skipping PR warnings.";
          exit 0;
        fi

      # Authenticate with GitHub (if token provided)
      - |
        if [ -n "$${PERSONAL_TOKEN:-}" ]; then
          echo "$${PERSONAL_TOKEN}" | gh auth login --with-token
          echo "Authenticated with GitHub"
        else
          echo "WARNING: PERSONAL_TOKEN not set. Skipping PR warnings."
          exit 0
        fi

      # Run stale branch warning
      - ./pipeline-utils/scripts/warn-stale-branches.sh
          --stale-days "$${STALE_DAYS}"
          --abandoned-days "$${ABANDONED_DAYS}"
          $${MENTION_TEAM:+--mention-team}
          $${MENTION_ASSIGNEES:+--mention-assignees}
          $${DRY_RUN:+--dry-run}

      - echo ""
      - echo "Stale PR warnings complete"
    secrets:
      - personal_token
    when:
      - event: cron
      - branch:
          include: [ main, develop, master ]

  ######################################
  # Step 3: Delete Merged Branches
  ######################################
  delete-merged:
    image: android-ci:latest
    name: "Delete Merged Branches"
    environment:
      TARGET_BRANCHES: "main develop"
      MERGED_RETENTION_DAYS: "${MERGED_RETENTION_DAYS}"
      DRY_RUN: "${DRY_RUN}"
    commands:
      - echo "=== Deleting Merged Branches ==="

      # Safety check: Confirm we're in a git repo
      - if ! git rev-parse --git-dir > /dev/null 2>&1; then
          echo "ERROR: Not a git repository";
          exit 1;
        fi

      # Show configuration
      - echo "Configuration:"
      - echo "  Target branches: $${TARGET_BRANCHES}"
      - echo "  Retention period: $${MERGED_RETENTION_DAYS} days"
      - echo "  Dry run: $${DRY_RUN}"

      # Run merged branch deletion
      - ./pipeline-utils/scripts/delete-merged-branches.sh
          --target "$${TARGET_BRANCHES}"
          --days "$${MERGED_RETENTION_DAYS}"
          $${DRY_RUN:+--dry-run}
          --force

      - echo ""
      - echo "Merged branch cleanup complete"
    when:
      - event: cron
      - branch:
          include: [ main, develop, master ]
      # Only run on main/develop branches for safety
      evaluate: "CI_BRANCH == 'main' || CI_BRANCH == 'develop' || CI_BRANCH == 'master'"

  ######################################
  # Step 4: Update Branch Status in DB
  ######################################
  update-status:
    image: android-ci:latest
    name: "Update Branch Status"
    environment:
      LOG_TO_DB: "true"
    commands:
      - echo "=== Updating Branch Status in Database ==="

      # Check database connection
      - |
        if [ -n "$${DB_HOST:-}" ] && [ -n "$${DB_NAME:-}" ]; then
          echo "Database configured: $${DB_HOST}/$${DB_NAME}"
        else
          echo "WARNING: Database not configured. Skipping status update."
          exit 0
        fi

      # Update all branches status
      - ./pipeline-utils/scripts/update-branch-status.sh --all

      - echo ""
      - echo "Branch status update complete"
    secrets:
      - db_host
      - db_port
      - db_name
      - db_user
      - db_password
    when:
      - event: cron

  ######################################
  # Step 5: Generate Summary Report
  ######################################
  summary-report:
    image: android-ci:latest
    name: "Generate Summary Report"
    commands:
      - echo "=== Branch Cleanup Summary Report ==="
      - echo ""
      - echo "Generated: $(date -u +'%Y-%m-%d %H:%M:%S UTC')"
      - echo ""
      - echo "Reports available in build/ directory:"
      - ls -lh build/ 2>/dev/null || echo "  No reports generated"
      - echo ""
      - echo "=========================================="

      # Display stale branch report if available
      - if [ -f "build/stale-branches-report.json" ]; then
          echo "Stale Branches Summary:"
          cat build/stale-branches-report.json | jq -r '
            "  Total: \(.branches.active | length + .branches.stale | length + .branches.abandoned | length)",
            "  Active: \(.branches.active | length)",
            "  Stale: \(.branches.stale | length)",
            "  Abandoned: \(.branches.abandoned | length)"
          ' 2>/dev/null || echo "  Could not parse report"
        fi
    when:
      - event: cron

################################################################################
# Pipeline Configuration Notes:
#
# 1. Schedule: This pipeline runs daily at midnight UTC via cron trigger
#
# 2. Safety Features:
#    - Protected branches (main, develop, release/*) are never deleted
#    - Dry-run mode for testing (set DRY_RUN: "true")
#    - All deletions logged to database
#    - Notifications sent for deletions
#
# 3. Required Secrets:
#    - github_token: For PR warnings and GitHub operations
#    - db_host, db_port, db_name, db_user, db_password: For database logging
#
# 4. Environment Variables:
#    - BRANCH_STALE_DAYS: Days before branch is considered stale (default: 30)
#    - BRANCH_ABANDONED_DAYS: Days before branch is abandoned (default: 60)
#    - MERGED_RETENTION_DAYS: Days to keep merged branches (default: 7)
#    - DRY_RUN: Set to "true" to preview changes without executing
#
# 5. Testing:
#    - To test without making changes, set DRY_RUN: "true" in environment
#    - Run manually with: woodpecker exec -e DRY_RUN=true
#
# 6. Notifications:
#    - Deletions are automatically sent to configured channels
#    - See send-notification.sh for channel configuration
#
# For more information, see:
# - Feature 4 Documentation: (to be created)
# - Branch Strategy Config: pipeline-utils/config/branch-strategy.yaml
################################################################################
